### ISSUE TITLE
Default value for placeholders

### ISSUE THREAD

**Issue by praneenshakya** [jspaine/quill-placeholder-module#3]
I was looking for something like:

`{someplaceholder || 'default value'}`

where the user can **type** a default value with a provided syntax so, that i can leverage the default value and no errors occur during absence of placeholder value.

I noticed that, placeholder wrapper has been set with contenteditable attribute as **false** as shown: 
`wrapper.setAttribute('contenteditable', 'false')`

I am well aware that this saves a lot of time with validating syntax for placeholders, but it would have been nice if you allowed **options**  to control this behavior which obviously **defaults to false**.

**Comment by jspaine** [comment]
Hi, i'm not sure what you mean by

> no errors occur during absence of placeholder value

How you handle converting them to values is out of the scope of this module, but you should easily be able to set defaults.

For customizable defaults I'd imagine it could get complicated trying to do it in the editor, but should be easy to do outside.

If you really want it it might be possible something like an editable node next to the uneditable label, and clicking the placeholder could highlight the editable part?
