### ISSUE TITLE
Existing `span` elements are broken

### ISSUE THREAD

**Issue by jsiebern** [jspaine/quill-placeholder-module#4]
Hi, first off let me say: This is an awesome plugin and it works perfectly :-)

Well, except for this one issue I have with it:
When I have some default source that contains `span` elements (using `react-quill`, not sure if that makes a difference), the `className` property in the blot seems to be set too late to pick it up. Therefore all existing `span` elements are being converted. As I use inline styles instead of classes for all attributes like size, color, background etc., it is a real issue for me.

I forked your repo and played around a bit and it seems that when I set the `className` prop explicitly in the `src/placeholder-blot.ts`, it works just fine and it doesn't try to take over the existing spans (just the ones with the class as intended!).

```typescript
// ....
  class PlaceholderBlot extends Embed {
    static blotName = 'placeholder'
    static tagName = 'span'
    static className: string = 'ql-placeholder-content'
    static delimiters: Array<string>
    public domNode: HTMLElement
// ....
```

I'm not sure what can be done as I'm not that familiar with Quill yet, but just changing the register of the blot inside the module constructor didn't work.

Thanks for your great work!

**Comment by jspaine** [comment]
Ah, that's not good! I think you're right that it's from setting the className after registering the module. I moved the register call into the constructor and it seemed to work (apart from warnings about non-existent formats and overwriting modules). I'll see if I can think of a solution.

Thanks! Glad you find it useful!

**Comment by jspaine** [comment]
Hi, I published a new version, can you let me know if it fixes your issue?
