### ISSUE TITLE
Wrapping in `contenteditable` unnecessary?

### ISSUE THREAD

**Issue by jsiebern** [jspaine/quill-placeholder-module#5]
Hi, I believe that wrapping the node contents into a span with `contenteditable="false"` is unnecessary, I might be wrong though.

I believe that a similar code to this:
```typescript
const wrapper = document.createElement('span')
wrapper.setAttribute('contenteditable', 'false')
wrapper.appendChild(labelNode)
```
can be found in the `blots/embed` constructor, of which the `PlaceholderBlot` class inherits. My placeholders are therefore being double wrapped.

I might be wrong though, as I said in the other issue - I'm not too familiar with Quill yet :)

**Comment by jspaine** [comment]
Hi, yeah you would think, but it turned out slightly less buggy this way! I can't remember what the problem was exactly though.

I've been meaning to update this since quill 1.3.something to use the new InlineEmbed that handles this for you.

**Comment by jspaine** [comment]
I misunderstood you before, the contenteditable=false was added to the embed blot in Quill 1.3. This should be fixed too now.

**Comment by Vasudha84** [comment]
Any solution to this?

**Comment by Vasudha84** [comment]
Any solution to this?

**Comment by simon-contreras-deel** [comment]
> My placeholders are therefore being double wrapped.

Same problem here
