### ISSUE TITLE
Scroll function for placeholders?

### ISSUE THREAD

**Issue by prashanth1k** [jspaine/quill-placeholder-module#9]
Hello,
Is it possible to have placeholder drop-down scroll within the existing window (or with a specified height for drop-down )? I am experimenting placeholder functionality for 50+ fields and the UI today just opens all fields in a long drop-down. 

Thanks!

**Comment by ambrooo** [comment]
Just use CSS
```
.ql-snow .ql-picker.ql-expanded .ql-picker-options{
    max-height: 200px;
    overflow-y: scroll;
}
```
